# Generated by Django 4.0.1 on 2022-01-14 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('avatar', models.CharField(max_length=300, verbose_name='Avatar')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('gender', models.CharField(blank=True, max_length=10, null=True, verbose_name='Genero')),
                ('age', models.IntegerField(verbose_name='Edad')),
                ('description', models.CharField(max_length=200, verbose_name='Descripcion')),
                ('work', models.CharField(blank=True, max_length=100, null=True, verbose_name='Trabajo')),
            ],
        ),
    ]
