# Generated by Django 4.0.1 on 2022-05-17 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Archivo',
            fields=[
                ('id_arch', models.AutoField(primary_key=True, serialize=False, verbose_name='Código')),
                ('archivo_arch', models.FileField(max_length=300, null=True, upload_to='Archivos/Proyectos/%Y/%m', verbose_name='Archivo')),
            ],
            options={
                'verbose_name': 'Archivo',
                'verbose_name_plural': 'Archivos',
                'db_table': 'archivo',
                'ordering': ['id_arch'],
            },
        ),
        migrations.CreateModel(
            name='Articulo',
            fields=[
                ('id_art', models.AutoField(primary_key=True, serialize=False, verbose_name='Código')),
                ('titulo_art', models.CharField(max_length=100, verbose_name='Título')),
                ('enlace_art', models.CharField(default='', max_length=300, verbose_name='Enlace')),
                ('indexacion_art', models.CharField(max_length=100, verbose_name='Indexación')),
                ('desc_art', models.CharField(max_length=100, verbose_name='Desconocido')),
                ('autores_art', models.CharField(max_length=500, verbose_name='Autores')),
                ('issn_art', models.CharField(max_length=100, verbose_name='ISSN')),
            ],
            options={
                'verbose_name': 'Artículo',
                'verbose_name_plural': 'Artículos',
                'db_table': 'articulo',
                'ordering': ['id_art'],
            },
        ),
        migrations.CreateModel(
            name='Carousel',
            fields=[
                ('id_car', models.AutoField(primary_key=True, serialize=False, verbose_name='Código')),
                ('titulopr_car', models.CharField(max_length=50, verbose_name='Título principal')),
                ('titulosec_car', models.CharField(max_length=50, verbose_name='Título secundario')),
                ('subtitulo_car', models.CharField(max_length=100, verbose_name='Subtítulo')),
                ('imagen_car', models.ImageField(max_length=300, null=True, upload_to='Imagenes/Carousel/%Y/%m', verbose_name='Imágen')),
            ],
            options={
                'verbose_name': 'Carousel',
                'verbose_name_plural': 'Carousels',
                'db_table': 'carousel',
                'ordering': ['id_car'],
            },
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id_cat', models.AutoField(primary_key=True, serialize=False, verbose_name='Código')),
                ('nombre_cat', models.CharField(max_length=100, verbose_name='Categoría')),
            ],
            options={
                'verbose_name': 'Categoría',
                'verbose_name_plural': 'Categorías',
                'db_table': 'categoria',
                'ordering': ['id_cat'],
            },
        ),
        migrations.CreateModel(
            name='Congreso',
            fields=[
                ('id_con', models.AutoField(primary_key=True, serialize=False, verbose_name='Código')),
                ('titulo_con', models.CharField(max_length=100, verbose_name='Título')),
                ('autor_con', models.CharField(max_length=100, verbose_name='Autor')),
                ('anio_con', models.CharField(max_length=5, verbose_name='Año')),
                ('numero_con', models.CharField(max_length=5, verbose_name='Número de congreso')),
            ],
            options={
                'verbose_name': 'Congreso',
                'verbose_name_plural': 'Congresos',
                'db_table': 'congreso',
                'ordering': ['id_con'],
            },
        ),
        migrations.CreateModel(
            name='Contenido',
            fields=[
                ('id_con', models.AutoField(primary_key=True, serialize=False, verbose_name='Código')),
                ('titulo_con', models.CharField(max_length=100, verbose_name='Título')),
                ('descripcion_con', models.CharField(max_length=500, verbose_name='Descripción')),
                ('archivo_con', models.FileField(max_length=300, null=True, upload_to='Archivos/Contenido/%Y/%m', verbose_name='Archivo')),
                ('imagen_con', models.ImageField(max_length=300, null=True, upload_to='Imagenes/Contenido/%Y/%m', verbose_name='Imágen')),
                ('fecha_con', models.DateField(null=True, verbose_name='Fecha')),
                ('autor_con', models.CharField(max_length=100, verbose_name='Autor')),
            ],
            options={
                'verbose_name': 'Contenido',
                'verbose_name_plural': 'Contenidos',
                'db_table': 'contenido',
                'ordering': ['id_con'],
            },
        ),
        migrations.CreateModel(
            name='Libro',
            fields=[
                ('id_lib', models.AutoField(primary_key=True, serialize=False, verbose_name='Código')),
                ('titulo_lib', models.CharField(max_length=100, verbose_name='Título')),
                ('desc_lib', models.CharField(max_length=100, verbose_name='Desconocido')),
                ('autores_lib', models.CharField(max_length=500, verbose_name='Autores')),
                ('issn_lib', models.CharField(max_length=100, verbose_name='ISSN')),
                ('tipo_lib', models.CharField(default='N/A', max_length=100, verbose_name='Tipo')),
            ],
            options={
                'verbose_name': 'Libro',
                'verbose_name_plural': 'Libros',
                'db_table': 'libro',
                'ordering': ['id_lib'],
            },
        ),
        migrations.CreateModel(
            name='Miembro',
            fields=[
                ('id_miem', models.AutoField(primary_key=True, serialize=False, verbose_name='Código')),
                ('nombre_miem', models.CharField(max_length=100, verbose_name='Nombres')),
                ('apellido_miem', models.CharField(max_length=100, verbose_name='Apellidos')),
                ('correo_miem', models.CharField(max_length=100, unique=True, verbose_name='Correo')),
                ('telefono_miem', models.CharField(max_length=10, verbose_name='Teléfono')),
                ('imagen_miem', models.ImageField(max_length=300, null=True, upload_to='Imagenes/Miembros/%Y/%m', verbose_name='Foto')),
                ('cargo_miem', models.CharField(max_length=100, null=True, verbose_name='Cargo')),
                ('descripcion_miem', models.CharField(max_length=500, null=True, verbose_name='Descripción')),
                ('hvida_miem', models.FileField(max_length=300, null=True, upload_to='Archivos/Miembros/%Y/%m', verbose_name='Hoja de vida')),
                ('tipo_miem', models.CharField(default='N/A', max_length=100, verbose_name='Tipo')),
            ],
            options={
                'verbose_name': 'Miembro',
                'verbose_name_plural': 'Miembros',
                'db_table': 'miembro',
                'ordering': ['id_miem'],
            },
        ),
        migrations.CreateModel(
            name='PIntelectual',
            fields=[
                ('id_pin', models.AutoField(primary_key=True, serialize=False, verbose_name='Código')),
                ('titulo_pin', models.CharField(max_length=100, verbose_name='Título')),
                ('fecha_in', models.DateField(null=True, verbose_name='Fecha')),
            ],
            options={
                'verbose_name': 'P. Intelecutal',
                'verbose_name_plural': 'P. Intelectuales',
                'db_table': 'p_intelectual',
                'ordering': ['id_pin'],
            },
        ),
        migrations.CreateModel(
            name='Proyecto',
            fields=[
                ('id_pro', models.AutoField(primary_key=True, serialize=False, verbose_name='Código')),
                ('titulo_pro', models.CharField(max_length=100, verbose_name='Título')),
                ('fecha_pro', models.DateField(null=True, verbose_name='Fecha')),
                ('responsable_pro', models.CharField(max_length=100, verbose_name='Responsable')),
                ('investigadores_pro', models.CharField(max_length=500, verbose_name='Investigadores')),
                ('periodo_pro', models.CharField(max_length=50, verbose_name='Periodo')),
                ('descripcion_pro', models.CharField(max_length=500, verbose_name='Descripción')),
            ],
            options={
                'verbose_name': 'Proyecto',
                'verbose_name_plural': 'Proyectos',
                'db_table': 'proyecto',
                'ordering': ['id_pro'],
            },
        ),
        migrations.CreateModel(
            name='Tesis',
            fields=[
                ('id_tes', models.AutoField(primary_key=True, serialize=False, verbose_name='Código')),
                ('titulo_tes', models.CharField(max_length=100, verbose_name='Título')),
                ('anio_tes', models.CharField(max_length=4, verbose_name='Año')),
                ('directores_tes', models.CharField(max_length=500, verbose_name='Directores')),
                ('autores_tes', models.CharField(max_length=500, verbose_name='Autores')),
                ('universidad_tes', models.CharField(max_length=200, verbose_name='Universidad')),
                ('tipo_tes', models.CharField(default='N/A', max_length=100, verbose_name='Tipo')),
            ],
            options={
                'verbose_name': 'Tesis',
                'verbose_name_plural': 'Tesis',
                'db_table': 'tesis',
                'ordering': ['id_tes'],
            },
        ),
        migrations.CreateModel(
            name='Theme',
            fields=[
                ('id_th', models.AutoField(primary_key=True, serialize=False, verbose_name='Código')),
                ('nombre_th', models.CharField(max_length=100, verbose_name='Tema')),
                ('posicion_th', models.CharField(max_length=10, verbose_name='Posición')),
            ],
            options={
                'verbose_name': 'Tema',
                'verbose_name_plural': 'Temas',
                'db_table': 'theme',
                'ordering': ['id_th'],
            },
        ),
    ]
