# Generated by Django 4.0.1 on 2022-05-17 16:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('api', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='theme',
            name='fk_id_usu',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
        ),
        migrations.AddField(
            model_name='contenido',
            name='fk_id_cat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.categoria', verbose_name='Categoría'),
        ),
        migrations.AddField(
            model_name='archivo',
            name='fk_id_pro',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.proyecto', verbose_name='Proyecto'),
        ),
    ]
