# Generated by Django 4.0.1 on 2022-05-18 16:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pintelectual',
            old_name='fecha_in',
            new_name='fecha_pin',
        ),
    ]
