# Generated by Django 4.0.1 on 2022-01-27 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_contenido_archivo_con'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contenido',
            name='fecha_con',
            field=models.DateField(null=True, verbose_name='Fecha'),
        ),
    ]
