# Generated by Django 4.0.1 on 2022-05-18 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_rename_fecha_in_pintelectual_fecha_pin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='congreso',
            name='anio_con',
            field=models.CharField(max_length=4, verbose_name='Año'),
        ),
    ]
