# Generated by Django 4.0.1 on 2022-02-02 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_contenido_fecha_con'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contenido',
            name='archivo_con',
            field=models.CharField(max_length=200, null=True, verbose_name='Archivo'),
        ),
    ]
