# Generated by Django 4.0.1 on 2022-02-02 23:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_contenido_archivo_con'),
    ]

    operations = [
        migrations.RenameField(
            model_name='miembro',
            old_name='descripcio_miem',
            new_name='descripcion_miem',
        ),
    ]
