# Generated by Django 4.0.1 on 2022-02-03 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_rename_descripcio_miem_miembro_descripcion_miem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contenido',
            name='archivo_con',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Archivo'),
        ),
    ]
