# Generated by Django 4.0.1 on 2022-02-10 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_contenido_imagen_con'),
    ]

    operations = [
        migrations.AlterField(
            model_name='miembro',
            name='imagen_miem',
            field=models.ImageField(max_length=300, null=True, upload_to='Imageners/Miembros/%Y/%m', verbose_name='Foto'),
        ),
    ]
