# Generated by Django 4.0.1 on 2022-02-10 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_alter_miembro_imagen_miem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contenido',
            name='archivo_con',
            field=models.FileField(max_length=300, null=True, upload_to='Archivos/Contenido/%Y/%m', verbose_name='Archivo'),
        ),
        migrations.AlterField(
            model_name='contenido',
            name='imagen_con',
            field=models.ImageField(max_length=300, null=True, upload_to='Imagenes/Contenido/%Y/%m', verbose_name='Imagen'),
        ),
    ]
