# Generated by Django 4.0.1 on 2022-02-10 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_alter_contenido_archivo_con_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contenido',
            name='archivo_con',
            field=models.FileField(max_length=300, null=True, upload_to='Archivos/Contenido/%Y/%m', verbose_name='Archivo'),
        ),
        migrations.AlterField(
            model_name='contenido',
            name='imagen_con',
            field=models.ImageField(max_length=300, null=True, upload_to='Imagenes/Contenido/%Y/%m', verbose_name='Imagen'),
        ),
        migrations.AlterField(
            model_name='miembro',
            name='imagen_miem',
            field=models.ImageField(max_length=300, null=True, upload_to='Imagenes/Miembros/%Y/%m', verbose_name='Foto'),
        ),
    ]
