# Generated by Django 4.0.1 on 2022-02-12 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_alter_contenido_archivo_con_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Theme',
            fields=[
                ('id_th', models.AutoField(primary_key=True, serialize=False, verbose_name='Codigo')),
                ('nombre_th', models.CharField(max_length=100, verbose_name='Tema')),
                ('posicion_th', models.CharField(max_length=10, verbose_name='Posicion')),
            ],
            options={
                'verbose_name': 'Tema',
                'verbose_name_plural': 'Temas',
                'db_table': 'theme',
                'ordering': ['id_th'],
            },
        ),
    ]
