# Generated by Django 4.0.1 on 2022-02-16 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_theme'),
    ]

    operations = [
        migrations.AlterField(
            model_name='miembro',
            name='correo_miem',
            field=models.CharField(max_length=200, unique=True, verbose_name='Correo'),
        ),
    ]
